### PR TITLE
Prevent loading big pages

### PR DESCRIPTION
**Pull request by daoudclarke**

### CODE REVIEW

**Comment by ColinEspinas** [comment]
I'll check it after work @daoudclarke

**Comment by daoudclarke** [comment]
Hi Colin, that last commit should probably have gone into a different branch as it's a WIP change - feel free to review the rest though!

**Review by ColinEspinas — APPROVED** [review]
Never used readable streams before, really cool stuff!

**Comment by daoudclarke** [comment]
Ha yes! took me a while to figure out how to limit the download size but it works a treat.

**Pull request merged**
